---
abstract: 'access a JSON/Sereal/etc scalar string in a hash-like manner'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Scalar::Accessors::LikeHash
name: Scalar-Accessors-LikeHash
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  JSON: 2.00
  Moose: 2.00
  Sereal: 0
requires:
  Module::Runtime: 0
  Moose: 2.00
  Role::Tiny: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Scalar-Accessors-LikeHash
  homepage: https://metacpan.org/release/Scalar-Accessors-LikeHash
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-scalar-accessors-likehash
version: 0.001
